### ISSUE TITLE
<spoiler:"spoilerName">

### ISSUE THREAD

**Issue by ruslancnua** [digao-dalpiaz/DzHTMLText#19]
Hi could you add spoiler tag with name?

![2020-07-22_094118](https://user-images.githubusercontent.com/45718831/88143277-9ed3c880-cbff-11ea-8032-93387ca2da39.png)
When click list expands. Thank.

**Comment by digao-dalpiaz** [comment]
Hey,

Unfortunately this cant't be done, because the component is based on a static image, so there is no way to change it dynamically when some action occurs.

Thanks for your interest in the component.

**Comment by digao-dalpiaz** [comment]
Hey @ruslancnua ,

I am reopening this issue as I am currently refactoring the entire component and now this functionality is supported. I just implemented tags to support "spoiler".
I'm working on it and it will be available soon.

**Comment by ruslancnua** [comment]
Thank you so much!

**Comment by digao-dalpiaz** [comment]
Done!
