### ISSUE TITLE
Support line-height

### ISSUE THREAD

**Issue by khongten001** [digao-dalpiaz/DzHTMLText#24]
Hi,

Thank you for your awesome component. Do you have plan to support css line-height property? Sometimes, I need to increase space between two lines!

**Comment by digao-dalpiaz** [comment]
Yes, it is possible to implement a property that will define the spacing between lines, but this would affect all lines of the text, it is not possible to specify exclusively between two lines.

**Comment by digao-dalpiaz** [comment]
Actually, it's possible to implement a new tag like this:

`<LS:10>some text</LS>`

This will add a line space of 10 pixels.

Or like this:

```
<LS:10>Some text line 1
Some text line 2
Some text line 3
<LS:2>Some text line 4</LS>   <-- a sub line space
Some text line 5
Some text line 6</LS>
```
This last example will print all lines using 10 pixels line spacing, but line 4 will have 2 pixels line spacing.

**Comment by digao-dalpiaz** [comment]
I also added a published **LineSpacing** property to define the default spacing.

**Comment by khongten001** [comment]
Awesome! Thank you for your work :)
