### ISSUE TITLE
Component Name conflit with commercial components HTML components

### ISSUE THREAD

**Issue by Rik69** [digao-dalpiaz/DzHTMLText#3]
Hi,
Your component use the same class name as the commercial components HTML components (https://www.delphihtmlcomponents.com/).

Erik

**Comment by digao-dalpiaz** [comment]
Interesting.
I had not seen this component yet.

I think I will change the class to TFmtLabel, because in fact my component is not exactly pure HTML.

Any way, thank you very much for letting me know.

**Comment by Rik69** [comment]
Just let me know if you rename it, I did it on my site to avoid conflict, but I had to do it also for Msg Dlg and you seem to update your component frequently so if you do it shortly, I will wait.

Thank you
Erik

**Comment by digao-dalpiaz** [comment]
Yeah sure, probably I'll change the name today to avoid any conflicts, otherwise it will be more difficult to change in working projects using this component.

I will post here and in the readme documentation.

**Comment by digao-dalpiaz** [comment]
Done!

Please full uninstall and delete older files before install new package.
If you are using the TDam component, it was updated too.
