### ISSUE TITLE
No text properties LbMsg: TDzHTMLText;

### ISSUE THREAD

**Issue by limelect** [digao-dalpiaz/DzHTMLText#30]
LbMsg: TDzHTMLText;
No text in the new component

**Comment by digao-dalpiaz** [comment]
Hi @limelect 

This property was **removed** in version 2.1 (now there is a TStrings property called "**Lines**"):

- 07/30/2020 (Version 2.1)

   - Implemented new Lines (TStrings) property and removed Text published property. :warning:
   - Implemented Text (String) public property as a shortcut to new Lines property. :warning:
   - Changed Lines (Integer) property name to LineCount. :warning:

     | :exclamation: Component property change. Risk of data loss! |
     |-------------------------------------------------------------|

     In order to keep TDzHTMLText Text string property content of your projects, you'll need to manually change property on DFM file, before opening projects in Delphi.
     Open the DFM files (using a text editor) that contains TDzHTMLText objects and replace as in the example:

     ```delphi
     object DzHTMLText1: TDzHTMLText
	   //FROM:
       Text = 'Line 1'#13#10'Line 2'#13#10'Line 3'
	   //TO:
       Lines.Strings = (
         'Line 1'#13#10'Line 2'#13#10'Line 3')
     end
     ```

     If you want to keep old Text property, please download the older version here: [TDzHTMLText v2.0](https://github.com/digao-dalpiaz/DzHTMLText/releases/tag/v2.0)

**Comment by limelect** [comment]
I do not understand. I have both HTMLText and the message (dam) updated to the new
packages.
I did not update?

**Comment by digao-dalpiaz** [comment]
I reviewed all demos (Dam and DzHTMLText) and they all updated and opening/running.

Can you post some screenshot?
Are you using Delphi or Lazarus?

Thanks.

**Comment by limelect** [comment]
The error persists.
Using D10.2.3 but it has nothing to do with Delphi.
![Screenshot - 27_10_2020 , 22_10_36](https://user-images.githubusercontent.com/4199131/97356913-a27f8700-18a1-11eb-9213-335c5bf4a48d.jpg)
![Screenshot - 27_10_2020 , 22_11_43](https://user-images.githubusercontent.com/4199131/97356918-a3b0b400-18a1-11eb-8148-223d53b275a6.jpg)
![Screenshot - 27_10_2020 , 22_12_00](https://user-images.githubusercontent.com/4199131/97356920-a3b0b400-18a1-11eb-8097-6216760f644b.jpg)
![Screenshot - 27_10_2020 , 22_12_23](https://user-images.githubusercontent.com/4199131/97356921-a4494a80-18a1-11eb-957f-d2daf5d0e373.jpg)




1. Downloaded again Dam and TDzHTMLText . 3'd time.
2. move sources to directories. (I sent you my DPK in ZIP).
3. Uninstall components.
 4. Build and compile
5. Install again components
6. Using large mes demo

**Comment by limelect** [comment]
Ok, I put in the option the source files link and it works.
Now I have to find why.

**Comment by digao-dalpiaz** [comment]
Ok, I got it.

Probably the problem is because the compiled .dcu files that Delphi are reading is outdated. When you are compiling the package, the .dcu files are generated in specific directory. So, when you are running any application, according to the library paths, these files might be reading from some other folder (outdated).

**Comment by limelect** [comment]
No, I am a professional since Delphi #1
But now I
![Screenshot - 27_10_2020 , 23_57_42](https://user-images.githubusercontent.com/4199131/97366603-42dca800-18b0-11eb-95a1-e04a76eb0090.jpg)
 have a different scenario
All dcu res and dfm of the last compile in one place.
Unless I put the directory link in the option I get the above error.

Let me just point that before the update I did not have so much trouble with your component

**Comment by limelect** [comment]
![Screenshot - 28_10_2020 , 00_03_41](https://user-images.githubusercontent.com/4199131/97367046-1c6b3c80-18b1-11eb-9901-d636eedc0a83.jpg)
And the result you can see on the buttons

**Comment by digao-dalpiaz** [comment]
It seems something about Language Resource file (Dam).

About a month ago, I have change Encoding of resource file because was not supporting some Languages (unicode).

It's strange because I'm testing here in different Delphi versions and everything seems to be fine.

If you are downloading components sources directly from Git commands, maybe Git is not recognizing file Encoding changes. If you are downloading directly from RAW mode, that is the problem at all. If you are downloading .zip file, then it's really strange behavior.

**I'll suggest you to DELETE these files:**
- Dam_Resource.RES
- Dam_Lang.ini

And then, download them from .ZIP, to keep correct file encoding.

**Comment by digao-dalpiaz** [comment]
I have tested here creating a new package and including all source in a sub-directory (just like you have there).

And I tried to use Library Path to .dcu files (/Win32/Release), and also using Library Path directly to Source files.

In all of these cases, everything worked normally.

**Comment by limelect** [comment]
What I have is a directory WITHOUT THE SOURCES!!! only All dcu res and dfm of the last compile in one place.
Only if I link to sources then it is OK.

**Comment by limelect** [comment]
Funny as it sounds I copied the third time the dcu dfm and res and now it is OK
Sorry.

**Comment by limelect** [comment]
One thing plz needed Extensive HELP

**Comment by digao-dalpiaz** [comment]
OK. 
About Dam help, there is a lot of information in GitHub Readme.
I'm trying to increase this readme whenever I can.
If is there any question, please open an Issue, so I can include it in the help.
Best regards.
