### ISSUE TITLE
Link-relative events more powerful suggestion?

### ISSUE THREAD

**Issue by LivingInFHL** [digao-dalpiaz/DzHTMLText#4]
Would you please add display-support for links in DzHTMLText ?

```
  THTEvLink = procedure(Sender: TObject; LinkID: Integer; Target: String; Display: String)
    of object;
  THTEvLinkClick = procedure(Sender: TObject; LinkID: Integer; Target: String;  Display: String;
    var Handled: Boolean) of object;
```

<a:www.google.com>Open Google Search</a>
<a:www.baidu.com>Open Baidu Search</a>

Sometimes I want to get '**Open Google Search**' or '**Open Baidu Search**' in OnLinkClick Event.
By the parameter of 'Display: string'.

Sometimes I want to get LinkId, Target , and also Display. To do some wonderful jobs.
That wil make TDzHTMLText more powerful.

Thank you very much. Great job.

**Comment by LivingInFHL** [comment]
Enhancement. Good.

**Comment by digao-dalpiaz** [comment]
Done!

Please read the documentation changes.
Thanks for the suggestion.
