### ISSUE TITLE
TDzHTMLText.Click - bug

### ISSUE THREAD

**Issue by Chandlr** [digao-dalpiaz/DzHTMLText#43]
Sorry iam new to github and writing reports but i found this bug in OnLinkClick

located in:
> procedure TDzHTMLText.Click;

Something like this is needed:
> if Assigned(Link.LinkRef) then

in case user does:
> str:=Link.LinkRef.Text;

Hope it helps locating the bug :)

**Comment by digao-dalpiaz** [comment]
Hello @Chandlr 

Are you using `<spoiler>` or `<a>` tag?

Can you please send more information about how to reproduce this bug?

Thanks.

**Comment by Chandlr** [comment]
> procedure TForm1.LblInfo2LinkClick(Sender: TObject; Link: TDHBaseLink;
>   var Handled: Boolean);
> var
> J,ID: Dword;
> nam: string;
> begin
> Handled:=True;
> nam:=Link.LinkRef.Text; <- This causes the bug
> end;


your example by trying using a spoiler click event:
<spoiler:name>This is the spoiler link text</spoiler><sdetail:name>This is the detail div that will be expanded when the spoiler link is clicked.</sdetail>

**Comment by digao-dalpiaz** [comment]
OK, in that case, you need to use `Link.Spoiler.Name` instead, because you are using a Spoiler tag instead a Link tag.

The `TDHBaseLink` object can be of two kinds (according to the link tag used):
- TDHLinkRef
- TDHSpoiler

You can get full information in this part of README:
https://github.com/digao-dalpiaz/DzHTMLText#link-object

**Comment by Chandlr** [comment]
i guess its possible todo a 

```
case Link.Kind of
lkSpoiler: nam:='';
lkLinkRef: nam:=Link.LinkRef.Text;
end;
```

assigned check

**Comment by digao-dalpiaz** [comment]
Yes, sure.
If you are dealing with both link kinds, you should check what kind of link is it when handling `OnLinkClick` event.

**Comment by Chandlr** [comment]
Indeed iam using both:

in beginning i have todo this:

```
  case Link.Kind of
  lkSpoiler: nam:='';
  lkLinkRef: nam:=Link.LinkRef.Text;
  end;
```

...

and in the end of code do the handle.

```
 case Link.Kind of
  lkSpoiler: Handled:=False;
  lkLinkRef: nam:=Link.LinkRef.Text;
  end;
```

**Comment by digao-dalpiaz** [comment]
Right, 

Just a note:
`Handled := False` is not necessary, it's the default value when event is triggered.

I don't know the whole purpose of your code, but if you are using Link Ref and Spoiler in HTML and you want to handle only Link Ref, you could do this:

```delphi
begin
  if Link.Kind = lkLinkRef then
  begin
    Handled := True;
    nam := Link.LinkRef.Text;
    (...)
  end;
end;
```

So, with this code, when clicked over a Spoiler tag, the default behavior will be performed.
