### ISSUE TITLE
wrong render of 2 <li> items

### ISSUE THREAD

**Issue by Alexey-T** [digao-dalpiaz/DzHTMLText#48]
this code
```
procedure TForm1.FormCreate(Sender: TObject);
begin
  p.Color:= clYellow;
  p.Text:= '<b>Cuda<u>Text</u></b> is editor<br><ul><li>test1</li><li>test2</li></ul>';
end;   
```
gives wrong render of 2 LI tags. they must reside on 2 lines!
![Screenshot from 2021-04-18 22-01-49](https://user-images.githubusercontent.com/4154978/115157452-fff6d280-a091-11eb-963c-6e95e604db98.png)

**Comment by digao-dalpiaz** [comment]
Fixed.
