### ISSUE TITLE
DzHTMLText for Lazarus

### ISSUE THREAD

**Issue by jackdp** [digao-dalpiaz/DzHTMLText#5]
Hi, Digao!

I've ported your **DzHTMLText** component to Lazarus.

The changes are not very large: several IFDEFs, changing several units in the uses clause, `ShellExecute` replaced by `OpenURL`/`OpenDocument` (on Linux).

I also converted your sample program to Lazarus and compiled for Windows 32 & 64-bit and Linux 32 & 64-bit.
Source files and binaries can be found here: [http://www.pazera-software.com/_priv/ddp/DzHTMLText/index.html](http://www.pazera-software.com/_priv/ddp/DzHTMLText/index.html)

Tested with Lazarus 2.0.3 + Free Pascal 3.1.1

**Example program on Linux**
![Example program on Linux](http://www.pazera-software.com/_priv/ddp/DzHTMLText/Linux.png)

Your project **Dam** also looks very interesting. Thanks.

Regards, Jacek

**Comment by digao-dalpiaz** [comment]
Hey Jacek,

This is really great!

I'll carefully check your implementation and consider including it in the repository.
Thank you very much.

**Comment by digao-dalpiaz** [comment]
Hey @jackdp,

I finally got the time to evaluate your files.
So, after making some adjustments, everything is ready!
For example, in the component background color, which must be loaded according to the parent property.

Please let me know if there is anything else.
Thank you.
