### ISSUE TITLE
URL links raise a "Platform not supported" on iOS

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [digao-dalpiaz/DzHTMLText#54]
With a link of:

<a:http://www.apple.com>A clickable link</a>

A "Platform not supported" exception is raised when it is clicked on iOS within procedure TDzHTMLText.Click.
It looks like there's a missing case for IOS in that procedure.

**Comment by digao-dalpiaz** [comment]
Hello @MyBuzzTechnologies 

I fixed clickable link implementation on Mac and iOS.

I made a test on Mac:
![testing_link_macos](https://user-images.githubusercontent.com/46692097/126901313-f82580d0-4a92-4c5d-a83c-89ea5a782ab4.png)

**Could you please run a test on iOS device?**
Please use this branch: https://github.com/digao-dalpiaz/DzHTMLText/tree/ios-canvas-instance

Thanks!

**Comment by MyBuzzTechnologies** [comment]
Thank you. I'll test this in the morning and let you know what happens

**Comment by digao-dalpiaz** [comment]
Hello @MyBuzzTechnologies ,

You were able to test the links on iOS?

**Comment by MyBuzzTechnologies** [comment]
Sorry for not coming back to you soon. I tested your fix and it works perfectly. Thank you for fixing so quickly!
