### ISSUE TITLE
Idea: Scrolls ?

### ISSUE THREAD

**Issue by Chandlr** [digao-dalpiaz/DzHTMLText#55]
Hi iam wondering if you could add scrollbars in the tags :)
eg:

<: div style="overflow-y: scroll;":>long text here then scrolls<:/div:>

Also the version in about is still 3.5

**Comment by digao-dalpiaz** [comment]
Hello @Chandlr 

I will analyze the possibility of including this feature.

About the version, yes, it's an error between VCL and FMX version.
There is a new version 3.7 coming soon. This is already fixed in new version.

**Comment by digao-dalpiaz** [comment]
Hello,

So, I was thinking... we could make the scroll bar for the whole component, using a property for that.

In the other hand, using tags to apply scroll bars is much more complex, because the component does not support fixed size area text (by height).

**Comment by Chandlr** [comment]
Hi :)
Do as you please but it would indeed be prettier using the complex way, no idea how it would look yet but the property for scrollbars would work also.
So go for which solution you find better :)

**Comment by jonahzheng** [comment]
@digao-dalpiaz hi,how does DzHTMLText set scroll?
I use TVertScrollBox as parent of DzHTMLText, but It is not fluency.

**Comment by digao-dalpiaz** [comment]
@jonahzheng ,

The component does not include scroll bars feature. But you can use TScrollBox and insert DzHTMLText inside the Scroll Box component, using auto height and fixed width.

**Comment by jonahzheng** [comment]
yes, I use TScrollBox, but scrolling isn't as smooth in ios.
it is as smootch in windows.

**Comment by digao-dalpiaz** [comment]
@jonahzheng Please, try to apply a background color in DzHTMLText component, because when you leave the background color null, the component will use transparent behavior, so you can get flickering due to transparency painting.
Using fixed background color may avoid flickering when repainting component (occurs when you are moving scroll bar)

**Comment by digao-dalpiaz** [comment]
Hello @jonahzheng , 
Did the scroll bar work correctly when using background color?

**Comment by digao-dalpiaz** [comment]
Closing the issue as there was no more information.
