### ISSUE TITLE
Want  a procedure like Measure()

### ISSUE THREAD

**Issue by GitCnSH-DSLIN** [digao-dalpiaz/DzHTMLText#6]
Please give a method like OnMeasure() of some other Delphi components,  So user can draw the HTML at a right location in some case. Thanks!

**Comment by digao-dalpiaz** [comment]
Hey @GitCnSH-DSLIN,

I don't think I understand exactly what you want.

Do you want to handle paint event to specify words positions? Or do you want to handle words calc method to set the x/y position of the words?

Please give me an example of a use case.

Thanks for enjoying the component.

**Comment by GitCnSH-DSLIN** [comment]
I am so sorry for my poor English!

I want to draw a HTML style text on canvas in my application, but I want to know where to draw it correctly and may not really draw it in some case. So if it has a procedure like OnMeasure() to know the exact size (whole height and width) of these  HTML text will be good.

**Comment by digao-dalpiaz** [comment]
Ok, if I got it right, you need to know Text Width and Height.

The component has two properties: **TextWidth** and **TextHeight** (read-only), so you can use them to adjust size of other parent components.

Besides that, there are another two properties, **AutoWidth** and **AutoHeight**. When these properties are enabled, the bounds of component area are automatically resized according the text length.

Please let me know if these properties will be useful to your case.

**Comment by GitCnSH-DSLIN** [comment]
Yes, that's fine, but after set the text, It will paint to the canvas  immediately, But I don't need it paint at this time. I hope that after setting all the properties, then I can use Rebuild() method to get the width and height of the this control, without drawing. So may need move Rebuild() method from private to public.

**Comment by digao-dalpiaz** [comment]
Hey @GitCnSH-DSLIN,

Ok, I got it.
I'll create a new branch and implement an event feature.
So you need to analyse this branch and let me know if implementation satisfies your code and then I'll merge the branch to master.

**Comment by digao-dalpiaz** [comment]
So, I created a branch named "_measure-bounds_", with the new **BeginUpdate/EndUpdate** feature.

You can use like this:
```
  DzHTMLText1.BeginUpdate;
  try
    DzHTMLText1.Text := 'Text <b>test</b> 1234';
    DzHTMLText1.Font.Color := clRed;
    DzHTMLText1.Font.Size := 20;
  finally
    DzHTMLText1.EndUpdate;
  end;
```

You can change all settings and text property without rebuild and repaint when in updating transaction. At this time, you can even read TextWidth and TextHeight properties.

About calling Rebuild directly, I think that's not a good idea because of component structure.
Please let me know if this is the way.

**Comment by GitCnSH-DSLIN** [comment]
You are so great! I only improved a little bit, please see my version of this code, thank you!  

https://github.com/GitCnSH-DSLIN/DzHTMLText/tree/e1a7cb6ef6947ca6a453a23dce974e5af4470ceb

**Comment by digao-dalpiaz** [comment]
Hey @GitCnSH-DSLIN,

Thanks for the feedback.
Feel free to improve the component in your fork repository.
Please let me know if some suggestion.

Regards.
