### ISSUE TITLE
FMX?

### ISSUE THREAD

**Issue by PolywickStudio** [digao-dalpiaz/DzHTMLText#62]
Does this work with Delphi FMX?

**Comment by digao-dalpiaz** [comment]
Hello,

Yes, it does.
You can use Firemonkey with Mac, iOS, Android, Windows.

The component works with Lazarus too, allowing Windows and Linux environments.

**Comment by PolywickStudio** [comment]
it works on iOS, Android, Mac OSX64, Mac OSXARM64.
