### ISSUE TITLE
What to you think about a tag for line like below

### ISSUE THREAD

**Issue by avmaksimov** [digao-dalpiaz/DzHTMLText#63]
I mean like this:
![image](https://user-images.githubusercontent.com/2793938/146685813-8aa88eaa-ef94-4ded-aff4-c04bae70f03b.png)

This I made in Paintbox. For me it seems well, but I don't want to extend my functionality because you have except line.

It would be great if you add the tag <line[:20]>. 20 = 20px and if we don't write any value, so this means that line have to be to the end of width.

So. I would write the next tag in your label  if you add this function: **<line:20> Action for <b>Edit</b> <line>** .

What do you think about it?

**Comment by digao-dalpiaz** [comment]
Hello,

It's a good idea.

Let me analyze some options:
- Line color
- Line height
- Line span between text
- Text position in line

**Comment by avmaksimov** [comment]
Thank you for your answer. Please think about:
1) on screen you see one canvas line after another (`LStyle.GetSystemColor(clBtnShadow)` and below `LStyle.GetSystemColor(clBtnHighlight)`);
2) the first line is better to see than it's in the middle or in the middle + 1 of TextHeight (`Ceil(TextHeight(vText) / 2`).

I suggested you on the first message line with only width in pixel. So it could always be in the middle of the text and always like "lowered bevel" in TBevel.
But if you want to add color, please add "lowered" that means two line one by one.

And about line span - I think it could be solved by adding text spaces)).

**Comment by digao-dalpiaz** [comment]
Maybe something like that:

<line:width=100;height=1;color=clRed;color2=clBlue;textspan=5;textmargin=20>Display Text</text>

- Width: width of line in pixels (optional - if blank, width is 100%)
- Height: height of each line in pixels (optional - if blank, height is 1px)
- Color: color of first line
- Color2: color of second line (optional, if blank, there is no second line)
- TextSpan: space in pixels between line and text (optional, if blank, space is 8px)
- TextMargin: where the text begins print from the left of the line, in pixels (optional, if blank, is 24px)

**Comment by avmaksimov** [comment]
I don't understand the difference between TextSpan and TextMargin. Please explain.
And how the place for the line would be calculated? May be in pixels? Because your component can change font size.

**Comment by digao-dalpiaz** [comment]
TextSpan x TextMargin:
![image](https://user-images.githubusercontent.com/46692097/147602605-a8d68004-6a80-4148-bad6-0eb1342cc6ff.png)

I think the line should be always centered in the whole line height.

**Comment by avmaksimov** [comment]
Thank you. Great! But please the line be nearer to the end of line when the height is odd. 
When you can do this?)

**Comment by digao-dalpiaz** [comment]
Hello, I'm refactoring some component methods to support this feature... 
Sorry, but this is taking longer than I would like...

**Comment by avmaksimov** [comment]
> Hello, I'm refactoring some component methods to support this feature... Sorry, but this is taking longer than I would like...

No problem. Later is better than never :).

**Comment by digao-dalpiaz** [comment]
Hello,

I'm finishing this now...

**Comment by digao-dalpiaz** [comment]
![image](https://user-images.githubusercontent.com/46692097/230247953-0b875a67-e475-46d0-9e19-705a4e762c7f.png)

**Comment by digao-dalpiaz** [comment]
Done!
