### ISSUE TITLE
Canvas not present when using FMX Frame

### ISSUE THREAD

**Issue by LecturePress** [digao-dalpiaz/DzHTMLText#65]
Using the installed component on Delphi 10.4.2
On design-time, dropped a TDzHTMLText, with a sample text :
<B>Hello</B>

On running the app : Exception $C0000005 with message : access violation at 0x00f90832: read of address 0x00000074,
The debug show the problem at "TTokensProcess.Create"

P.S : Package installed manually

**Comment by digao-dalpiaz** [comment]
Hello @LecturePress ,

- Are you using the last version? (3.9)
- Are you using VCL or FMX?

**Comment by LecturePress** [comment]
I was using the latest repo zip, on FMX framework.
That bug did not occur on previous version (November 2021)

**Comment by digao-dalpiaz** [comment]
Ok, but the last version was released on November 2021.

I created the same app here in FMX environment, and running the app without errors.

Can you check your Library Path to ensure .DCU used by Runtime is the same as you are compiling the component ?

**Comment by LecturePress** [comment]
The unit (FMX.DzHTMLText.pas) is included directly in the project.

Putting the TDzHTMLText on a form in designtime, the app works fine, no problems.

But, putting the TDzHTMLText on a frame (FMX frame) in designtime, then creating that frame in the main form on runtime, the app will crash with (Exception $C0000005 at TTokensProcess.Create ...) at the moment when you call the method for creating the frame.

Here is the code used for frame creation :

MyFrame := TFrameAPP.Create(Self);
MyFrame .Name := 'MyFrame' + I.ToString;
MyFrame .Parent := Tab2;
MyFrame .Align := TAlignLayout.Client;

**Comment by digao-dalpiaz** [comment]
Ok, got it.
I found the bug. Fixing it now...

**Comment by digao-dalpiaz** [comment]
Done. New version 3.10 available!

**Comment by LecturePress** [comment]
It is working perfectly,
Nice job
