### ISSUE TITLE
DPI Support, for Tag <T:##>, <TF:##>, <FLOAT ##>, <LS:##>

### ISSUE THREAD

**Issue by WeberAndre** [digao-dalpiaz/DzHTMLText#68]
On different DPI's the values of these tags should be scaled to FCurrentPPI durring parsing / loading from the string. I would assume that these values are pixels @ 96 DPI Resolution and should scaled f.e. with  MulDiv( value, FCurrentPPI, 96 );

**Comment by digao-dalpiaz** [comment]
Hello

Can you please test this new feature?

Available at: https://github.com/digao-dalpiaz/DzHTMLText/tree/font-dpi

**Comment by WeberAndre** [comment]
I made a quick review of the new code and compared it with my "changes" fixes - most seems to be equal but some issues are sill left - I attach a textfile with my comments.  I'am reading / writing with VCL in mind, I have no experience with FMX - may be there it must be done in an other way?
 
[review.txt](https://github.com/digao-dalpiaz/DzHTMLText/files/8369904/review.txt)

**Comment by digao-dalpiaz** [comment]
Estou fazendo uma nova revisão sobre o suporte a DPI. Está quase pronto o suporte para VCL.

https://github.com/digao-dalpiaz/DzHTMLText/tree/dpi-support

**Comment by digao-dalpiaz** [comment]
I'm doing a new review on DPI support. VCL support is almost ready.

https://github.com/digao-dalpiaz/DzHTMLText/tree/dpi-support

**Comment by digao-dalpiaz** [comment]
Done! Available in next version
