### ISSUE TITLE
A bug while set text alignment to AlignCenter or AlignRight 

### ISSUE THREAD

**Issue by GitCnSH-DSLIN** [digao-dalpiaz/DzHTMLText#7]
Code like this:
procedure TForm1.btn1Click(Sender: TObject);
begin
&nbsp;&nbsp;Lb := TDzHTMLText.Create(Self);
&nbsp;&nbsp;Lb.Parent := Self;
&nbsp;&nbsp;with Lb do begin
&nbsp;&nbsp;&nbsp;&nbsp;Visible := True;
&nbsp;&nbsp;&nbsp;&nbsp;BeginUpdate;
&nbsp;&nbsp;&nbsp;&nbsp;try
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Left := 100;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Top := 100;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Width := 10;  // Very small for test
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Height := 10; // Very small for test
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Font.Color := clWindowText;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Font.Height := -13;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Font.Name := 'Segoe UI';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Font.Style := [];
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Text := '&lt;r&gt;AAA&lt;/r&gt;&lt;br&gt;XX';
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AutoWidth := True;  //hope to show whole "AAA“
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AutoHeight := True;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Images := MyImages;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OnLinkClick := LbLinkClick;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LineVertAlign := vaCenter;
&nbsp;&nbsp;&nbsp;&nbsp;finally
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;EndUpdate(True);
&nbsp;&nbsp;&nbsp;&nbsp;end;
&nbsp;&nbsp;end;
end;

but the AAA will not be drawn correctly, all because of this code:
  procedure DoLineBreak;
  begin
&nbsp;&nbsp; ......
&nbsp;&nbsp;LGroupBound.Add(Lb.Width); // add line bound to use in group align -- This has some problems
    ......
  end;

**Comment by digao-dalpiaz** [comment]
Hey @GitCnSH-DSLIN,

Thanks for reporting this bug.

I fixed it right now.
