### ISSUE TITLE
Delphi 10 Seattle

### ISSUE THREAD

**Issue by albertofll** [digao-dalpiaz/DzHTMLText#71]
Installing the component with Delphi 10 Seattle it raise an error at this code:

`function GetDesignerPPI(F: TCustomForm): Integer;
begin
  Result :=
    {$IFDEF FPC}
    F.PixelsPerInch
    {$ELSE}
      **{$IF CompilerVersion >= 30} //D10 Seattle**
      TFormScaleHack(F).GetDesignDpi
      {$ELSE}
      TFormScaleHack(F).PixelsPerInch
      {$ENDIF}
    {$ENDIF};
end;`

D10 Seattle don't implement GetDesignDpi, so the conditional must be {$IF CompilerVersion >= 31} to install correctly.

**Comment by digao-dalpiaz** [comment]
Fixed!
