### ISSUE TITLE
When CMFontchanged is triggered by Delphi's ScaleForPPI in a Frame constructor, it generates a GPF

### ISSUE THREAD

**Issue by PlanetIrata** [digao-dalpiaz/DzHTMLText#73]
My Delphi app is developped at 144dpi. When I run it on my 144dpi monitor, it perfect. But when running it on a 96dpi monitor, Delphi calls `TControl.ScaleForPPI` is run for every control by the constructor and work with all controls but the `TDzHTMLText`. 

The event `TDzHTMLText.CMFonchanged` calls to `BuildAndPaint` leads to a GPF due to issues with controls not having parents.

If I modify `TDzHTMLText.CMFonchanged` to `Exit` immediately without calling `BuildAndPaint`, no more Issues, my app runs smoothly without any error.

Seems that calling `BuildAndPaint` from a constructor is not safe.

Thanks for your help.

**Comment by digao-dalpiaz** [comment]
Trying to reproduce this problem right now...

**Comment by digao-dalpiaz** [comment]
I couldn't reproduce the same problem here, but I understood the scenario.

I created a possible fix. I ask you to update your component with this branch and do a test:
https://github.com/digao-dalpiaz/DzHTMLText/tree/component-loading-interface-ctrl

Thanks

**Comment by PlanetIrata** [comment]
Hi, tested the branch and it seems to solve the Issue, no more GPF!

Thanks

**Comment by PlanetIrata** [comment]
Sorry, GPF still occurs...

**Comment by digao-dalpiaz** [comment]
Hello @PlanetIrata , 
What version of Delphi are you using?

**Comment by PlanetIrata** [comment]
Delphi 11 Alexandria Update 1

**Comment by digao-dalpiaz** [comment]
Hello @PlanetIrata,

I am currently refactoring the component engine.  (#78)
One of the things that has already been refactored is the issue of DPI adjustment. Perhaps with this refactoring the problem will be resolved.
I ask that you wait until the RC version is available. I'll let you know so you can test it out.

Thanks.

**Comment by digao-dalpiaz** [comment]
Version available for testing purposes:
https://github.com/digao-dalpiaz/DzHTMLText/tree/engine-refact

**Comment by digao-dalpiaz** [comment]
Hello,
New version 5.0 available, with some refatoring in Scaling methods. Please run a new test!

**Comment by digao-dalpiaz** [comment]
Hello @PlanetIrata ,

Have you tried testing the new version?

**Comment by PlanetIrata** [comment]
Hi @digao-dalpiaz, yes it works perfectly now with the version 5. I close ! Many thanks
