### ISSUE TITLE
i can't inatall Dam dialog ?!

### ISSUE THREAD

**Issue by MajidAshouri** [digao-dalpiaz/DzHTMLText#76]
Hi
please help or guide me

i want to insatll dam diaolg https://github.com/digao-dalpiaz/Dam

at fiirst i should install DzHTMLText https://github.com/digao-dalpiaz/DzHTMLText

but aftre i installed DzHTMLText  , my lazarus damaged and didn't run ?

what is run ?
![Uploading Capture.PNG…]()

shcore.dll not find??!?!?

https://forum.lazarus.freepascal.org/index.php/topic,65407.0.html

**Comment by digao-dalpiaz** [comment]
Done!
