### ISSUE TITLE
Add Heading levels support

### ISSUE THREAD

**Issue by LecturePress** [digao-dalpiaz/DzHTMLText#77]
I saw a similar project (maybe a fork) having support of Heading levels : the HTML text has the heading tags (`<h1>` `<h2>` `<h3>` ...) and there is properties for customizing the appearance of every level apart.

It would be nice to have support for the six heading levels in this project in order to show a text with multi heading levels, suitable for projects like an encyclopedia, an ebook or a blog app (native components not webview).

**Comment by digao-dalpiaz** [comment]
Testing new feature....

**Comment by digao-dalpiaz** [comment]
Testing version available at:
https://github.com/digao-dalpiaz/DzHTMLText/tree/engine-refact

**Comment by digao-dalpiaz** [comment]
Done!
