### ISSUE TITLE
Unable to install DzHTMLText v6.0

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [digao-dalpiaz/DzHTMLText#86]
When I follow the instructions to manually install the latest (v6.0) component, it builds the first two packages without problems, but fails to build the TextDesign ones (VCL or FMX) with an error "unable to find required package DzHTMLText.dcp".

I've checked the default folder (c:\public\document\embarcadero\22.0\Dcp and Bpl) and the necessary files are in the folder.

This is a clean install of v6.0 - all previous bpl, hpp, dcp etc were deleted before trying to build.

**Comment by digao-dalpiaz** [comment]
Please do the following test: compile only the Runtime packages (these are the packages WITHOUT the "Design" suffix) and check if the .dcp files appear in the Users/Public/Embarcadero/Studio/22.0/Dcp/ folder.

When these packages are compiled, these files must be generated in this folder.
These are the files that are read by Runtime packages.

**Comment by MyBuzzTechnologies** [comment]
The runtime packages compile ok, and generate the Dcp files in the correct folder (the one you mentioned).
However, the design time packages still won't build due to not being able to find the Dcp packages.

**Comment by MyBuzzTechnologies** [comment]
Thanks. I did a full clear + reinstall:
1. Component > Install Packages > Remove all DzHTMLText packages
2. Closed Delphi
3. Deleted the local sources and re-cloned from your GitHub
4. Deleted all DzHTML*.* from the c:\Users\Public\Documents\Embarcadero\22.0\* folders (Dcp, hpp, bpl)
5. Re-opened the groupproj from your sources.
6. This time, the runtime and design time packages built ok 👍🏻

However - when I tried to install the design time packages I'm seeing a weird EntryPoint error:

<img width="445" alt="image" src="https://github.com/digao-dalpiaz/DzHTMLText/assets/37405280/dcb7d1b8-06b1-41c3-bd8a-cbf0d1062e82">

**Comment by MyBuzzTechnologies** [comment]
Thanks Digao, it looks like I had a version in an old Delphi install folder that 11.3 was picking up. I cleared all those out and it installs correctly now.
Thanks for you help 🙏
