### ISSUE TITLE
Vcl.Forms TMonitor.GetPixelsPerInch Monitor nil

### ISSUE THREAD

**Issue by lovehyunju** [digao-dalpiaz/DzHTMLText#94]
An error occurred on a user’s computer while using my program, and I received detailed information about the error through madExcept.

exception class    : EAccessViolation
exception message  : Access violation at address 00C0AE96 in module 'XXXXXXXX.exe'. Read of address 00000004.

main thread ($247c):
00c0ae96 +022 XXXXXXXX.exe Vcl.Forms                  TMonitor.GetPixelsPerInch
00c6572c +030 XXXXXXXX.exe Vcl.DzHTMLText    1668  +6 TDzHTMLText.CalcMulDiv
00c65794 +000 XXXXXXXX.exe Vcl.DzHTMLText    1690  +0 TDzHTMLText.CalcScale
00c54ce6 +0d6 XXXXXXXX.exe Vcl.DHTokenEngine 1673 +26 TDHBuilder.Create
00c658bd +021 XXXXXXXX.exe Vcl.DzHTMLText    1771  +1 TDzHTMLText.CallTokenEngine
00c65856 +03a XXXXXXXX.exe Vcl.DzHTMLText    1751 +16 TDzHTMLText.Rebuild
00c6484c +018 XXXXXXXX.exe Vcl.DzHTMLText     943  +3 TDzHTMLText.Modified
00c64c8e +02e XXXXXXXX.exe Vcl.DzHTMLText    1221  +6 TDzHTMLText.Resize
00b4a460 +094 XXXXXXXX.exe Vcl.Controls               TControl.SetBounds
00b4afeb +17f XXXXXXXX.exe Vcl.Controls               TControl.ChangeScale
00b4ae2e +06a XXXXXXXX.exe Vcl.Controls               TControl.ScaleForPPI
00b54dde +0ba XXXXXXXX.exe Vcl.Controls               TWinControl.ScaleControlsForDpi
00b54d0b +0e3 XXXXXXXX.exe Vcl.Controls               TWinControl.ScaleForPPI
00b54dde +0ba XXXXXXXX.exe Vcl.Controls               TWinControl.ScaleControlsForDpi
00c01eec +0a0 XXXXXXXX.exe Vcl.Forms                  TCustomForm.ScaleForPPIRect
00c083cb +0b7 XXXXXXXX.exe Vcl.Forms                  TCustomForm.WMDpiChanged
00b4cc86 +2be XXXXXXXX.exe Vcl.Controls               TControl.WndProc
00bd17c9 +139 XXXXXXXX.exe Vcl.Themes                 TStyleHook.WndProc
00bd19aa +00a XXXXXXXX.exe Vcl.Themes                 TMouseTrackControlStyleHook.WndProc
00c1ccef +08b XXXXXXXX.exe Vcl.Forms                  TFormStyleHook.WndProc
00d8ed98 +094 XXXXXXXX.exe Vcl.Styles                 TStyleEngine.HandleMessage
00bcdaa0 +054 XXXXXXXX.exe Vcl.Themes                 TStyleManager.HandleMessage
00b5028f +00f XXXXXXXX.exe Vcl.Controls               TWinControl.DoHandleStyleMessage
768c91c1 +081 USER32.dll                               GetWindowLongW
00b51800 +02c XXXXXXXX.exe Vcl.Controls               TWinControl.MainWndProc
00ac4734 +014 XXXXXXXX.exe System.Classes             StdWndProc
77e854bb +04b ntdll.dll                                KiUserCallbackDispatcher
00da622d +125 XXXXXXXX.exe SecretDNS           57 +29 initialization
00da624d +145 XXXXXXXX.exe SecretDNS           58 +30 initialization
75cafcc7 +017 KERNEL32.DLL                             BaseThreadInitThunk

**Comment by digao-dalpiaz** [comment]
Please let me know which version of the component you are using.

**Comment by lovehyunju** [comment]
If you check by referring to README.md, it appears to be version 6.4.
- 03/26/2024 (Version 6.4)

**Comment by digao-dalpiaz** [comment]
I found the problem. I will release the fix soon.

**Comment by digao-dalpiaz** [comment]
Fixed!

**Comment by lovehyunju** [comment]
Thank you so much for addressing the issue so quickly! I really appreciate your effort and the prompt fix. Great work! 👍
